name: IAM Service

on:
  push:
    paths:
      - 'svc/iam/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.22
        uses: actions/setup-go@v2
        with:
          go-version: 1.22
        id: go

      - name: Unit Test
        run: go test ./svc/iam/...
      
      - name: Integration Test
        run: |
          docker compose up -d
          source ./test/integration/iam/source.sh
          go test ./test/integration/iam_test.go
